#!/bin/bash
# vim: set ft=sh

set -eu

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

cd $GOPATH/src/github.com/concourse/github-release-resource

go install github.com/concourse/github-release-resource/vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p "$@"

./scripts/build

cp -a assets Dockerfile $BUILD_DIR
